// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6qWNg-7uusMqcxWeOj-OolddSpBM5B6o',
    appId: '1:1080874588997:web:356dad3a3f434fe1e9fc2c',
    messagingSenderId: '1080874588997',
    projectId: 'circuflow-2891a',
    authDomain: 'circuflow-2891a.firebaseapp.com',
    databaseURL: 'https://circuflow-2891a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'circuflow-2891a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBEMy-769FuBt-hdPkqrrmZubuLyanP0c',
    appId: '1:1080874588997:android:ffa529c59c9a9e2ce9fc2c',
    messagingSenderId: '1080874588997',
    projectId: 'circuflow-2891a',
    databaseURL: 'https://circuflow-2891a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'circuflow-2891a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXLs0BQSLL0LRbs7JBu45cCdpwhDEiLA',
    appId: '1:1080874588997:ios:4c75203f31024ebfe9fc2c',
    messagingSenderId: '1080874588997',
    projectId: 'circuflow-2891a',
    databaseURL: 'https://circuflow-2891a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'circuflow-2891a.firebasestorage.app',
    iosBundleId: 'com.example.circuFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaXLs0BQSLL0LRbs7JBu45cCdpwhDEiLA',
    appId: '1:1080874588997:ios:4c75203f31024ebfe9fc2c',
    messagingSenderId: '1080874588997',
    projectId: 'circuflow-2891a',
    databaseURL: 'https://circuflow-2891a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'circuflow-2891a.firebasestorage.app',
    iosBundleId: 'com.example.circuFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6qWNg-7uusMqcxWeOj-OolddSpBM5B6o',
    appId: '1:1080874588997:web:f0459b1ce74125d4e9fc2c',
    messagingSenderId: '1080874588997',
    projectId: 'circuflow-2891a',
    authDomain: 'circuflow-2891a.firebaseapp.com',
    databaseURL: 'https://circuflow-2891a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'circuflow-2891a.firebasestorage.app',
  );
}
